id: A4F197B75
base_file: fF808.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:49:49.035913
  last_modified_at: 2022-06-19 17:49:49.035918
