id: A4F197B75
base_file: f464A.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:49:49.032083
  last_modified_at: 2022-06-19 17:49:49.032091
