id: A4F197B75
base_file: fA3A0.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:49:49.034148
  last_modified_at: 2022-06-19 17:49:49.034152
